version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_financeiro
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuaSenhaForte123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql # Persistência de dados garantida
volumes:
  sql_data: